version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/repos/linky-dist
hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: ubuntu
      timeout: 3600
  ApplicationStart:
    - location: scripts/start.sh
      runas: ubuntu
      timeout: 3600